### ISSUE TITLE
gcal feed shows original of recurring event

### ISSUE THREAD

**Issue by jeremyescott** [gangplank/gpfeeds#1]
per the gcal feeds api, we need to write code that identifies recurring events that are included in our query, re-run the pull for instances of those recurring events, and then feed those data to our JSON output

https://developers.google.com/google-apps/calendar/v3/reference/events/instances

This error is why hacknight is showing as some wednesday in 2010 on the cal, and same with brownbags.

FYI
https://developers.google.com/google-apps/calendar/v3/reference/events#resource

**Comment by davis9001** [comment]
We have a hacked fix on this... prefer better implementation.

**Comment by davis9001** [comment]
Used singleEvents=true on Google API URL, commented out crazy Ruby code. :)
