### ISSUE TITLE
case sensivity on twitter searches

### ISSUE THREAD

**Issue by jeremyescott** [gangplank/gpfeeds#15]
@GPChandler works
@gpchandler does not

**Comment by davis9001** [comment]
:( sadface...

**Comment by davis9001** [comment]
I'm closing this, seems to just be Twitter search weirdness, AKA not something we can fix.

This one showed up: https://twitter.com/allstruck/status/341385114699329537
But not this one: https://twitter.com/allstruck/status/341366377434722307

Grrrr.......
